#ifndef _RESPATH_
#define _RESPATH_


// picture, music
const char* picfiles[] = {
	"about_normal.png",
	"about_select.png",
	"AB_normal.png",
	"AB_select.png",
	"allow_walkLeft.png",
	"allow_walkRight.png",
	"arrow.png",
	"arrowActionL.png",
	"arrowActionR.png",
	"arrowBroken.png",
	"arrowBullet.png",
	"arrow_die.png",
	"axe.png",
	"backA.png",
	"backB.png",
	"background.png",
	"backKeyImage.png",
	"backKeyLeft.png",
	"backKeyRight.png",
	"backToMenu.png",
	"battery.png",
	"batteryBoom1.png",
	"batteryBoom2.png",
	"batteryBoom3.png",
	"batteryBullet.png",
	"bg.png",
	"blinkcoin.png",
	"boss.png",
	"bossBullet.png",
	"brokencoin.png",
	"bulletBorder.png",
	"CloseNormal.png",
	"CloseSelected.png",
	"cloud.png",
	"coinani.png",
	"controlUI.png",
	"darkCloud.png",
	"fireActionL.png",
	"fireActionR.png",
	"fireBall.png",
	"fireLeft.png",
	"fireRight.png",
	"fire_die.png",
	"flag.png",
	"flower0.png",
	"flyFishLeft.png",
	"flyFishRight.png",
	"fps_images.png",
	"gameover.png",
	"HelloWorld.png",
	"ladder.png",
	"left.png",
	"leftright.png",
	"lighting.png",
	"Mushroom0.png",
	"music_off.png",
	"music_on.png",
	"M_n.png",
	"M_s.png",
	"newgameA.png",
	"newgameB.png",
	"nextlevel_normal.png",
	"nextlevel_select.png",
	"normal_die.png",
	"PassFailure.png",
	"PassSuccess.png",
	"princess.png",
	"quitgame_normal.png",
	"quitgame_select.png",
	"restart_n.png",
	"restart_s.png",
	"resume_n.png",
	"resume_s.png",
	"retry_normal.png",
	"retry_select.png",
	"rewardMushroomSet.png",
	"right.png",
	"select_n.png",
	"select_s.png",
	"Setting_n.png",
	"setting_s.png",
	"Set_Menu.png",
	"Set_Music.png",
	"set_n.png",
	"set_s.png",
	"shanshuodecoin.png",
	"singleblock.png",
	"sliderProgress.png",
	"sliderTrack.png",
	"smallWalkLeft.png",
	"smallWalkRight.png",
	"small_die.png",
	"sound_effect_off.png",
	"sound_effect_on.png",
	"startgame_normal.png",
	"startgame_select.png",
	"superMarioMap.png",
	"switchBg.png",
	"Tools.png",
	"tortoise0.png",
	"walkLeft.png",
	"WalkLeft_fire.png",
	"walkRight.png",
	"WalkRight_fire.png",
};

const char *bgMusicFile[] =
{
	"OnLand.wav"
};

#if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
const char* effectMusicfile[] =
{
	"AddLife.ogg",
	"BossDiaoLuoQiaoXia.ogg",
	"BossDie.ogg",
	"BossHuoQiu.ogg",
	"CaiSiGuaiWu.ogg",
	"DiaoRuXianJingSi.ogg",
	"DingChuMoGuHuoHua.ogg",
	"DingPoZhuan.ogg",
	"DingYingZhuanKuai.ogg",
	"EatCoin.ogg",
	"EatMushroomOrFlower.ogg",
	"GameOver.ogg",
	"HuoQiuDaDaoGuaiWu.ogg",
	"Jump.ogg",
	"QiZiLuoXia.ogg",
	"RengHuoQiu.ogg",
	"SuoXiao.ogg",
	"YuDaoGuaiWuSi.ogg",
};
#endif

#if (CC_TARGET_PLATFORM == CC_PLATFORM_WIN32)
const char* effectMusicfile[] =
{
	"AddLife.wav",
	"EatCoin.wav",
	"EatMushroomOrFlower.wav",
	"SuoXiao.wav",
	"Jump.wav",
	"HuoQiuDaDaoGuaiWu.wav",
	"RengHuoQiu.wav",
	"CaiSiGuaiWu.wav",

	"DingChuMoGuHuoHua.wav",
	"DingPoZhuan.wav",
	"DingYingZhuanKuai.wav",

	"BossDiaoLuoQiaoXia.wav",
	"BossDie.wav",
	"BossHuoQiu.wav",

	"DiaoRuXianJingSi.wav",
	"YuDaoGuaiWuSi.wav",
	"GameOver.wav",
	"QiZiLuoXia.wav",

};

#endif

#endif //_RESPATH_