#include "SaveItemTemplate.h"

void SaveItemTemplate::InitData(void)
{
	isInstance = lastLoadLanguage != ConfigLanguageSetting::instance().getCurLanguageName() ? false : isInstance;
	
	if(isInstance) 
		return;

	Release();
	lastLoadLanguage = ConfigLanguageSetting::instance().getCurLanguageName();
	isInstance		 = true;
	SaveItemTemplate* temp;

	temp = new SaveItemTemplate();
temp->Key = "Save_001";
temp->savePreKey = "dream";
temp->count = 6;
temp->onlyPicture = false;
temp->scale = 0.3f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "Save_002";
temp->savePreKey = "snowman";
temp->count = 6;
temp->onlyPicture = false;
temp->scale = 1.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "Save_003";
temp->savePreKey = "bottle";
temp->count = 6;
temp->onlyPicture = false;
temp->scale = 1.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "Save_004";
temp->savePreKey = "garland";
temp->count = 6;
temp->onlyPicture = false;
temp->scale = 1.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "Save_005";
temp->savePreKey = "color";
temp->count = 6;
temp->onlyPicture = true;
temp->scale = 1.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "Save_006";
temp->savePreKey = "sugar";
temp->count = 6;
temp->onlyPicture = true;
temp->scale = 0.4f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));
temp = new SaveItemTemplate();
temp->Key = "";
temp->savePreKey = "";
temp->count = 0;
temp->onlyPicture = false;
temp->scale = 0.0f;
mapdata.insert(std::make_pair(temp->Key,temp));

}